import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Navigator from "../components/Navigator";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairo.variable} antialiased bg-white dark:bg-black`}>
          <div className="flex min-h-screen">
            <Navigator />
            <main className="flex-1 p-6">{children}</main>
          </div>
      </body>
    </html>
  );
}
