import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "@/app/globals.css";
import Navigator from "@/components/Navigator";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navigator />
      <main className="flex-1 p-6">{children}</main>
    </>
  );
}
