import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "@/app/globals.css";
import Aside from "@/components/Aside";
import React from "react";
import Header from "@/components/Header";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ar' dir="rtl">
      <body className={`${cairo.variable} antialiased bg-white dark:bg-black`}>
        <div className="min-h-screen flex flex-col" style={{ fontFamily: "var(--font-cairo)" }}>
          <Header className="md:hidden"></Header>
          <div className="flex flex-col-reverse md:flex-row sm:p-6 gap-6">
            <Aside />
            <main className="flex-1 overflow-hidden dark:bg-black rounded-lg py-10 px-6">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
